name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  actions: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref_name == 'master'
    steps:
      - uses: actions/checkout@v7
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Building
        run: bun run build

      - name: Deploying to Cloudflare Pages
        uses: cloudflare/wrangler-action@v4
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=eveeifyeve
