name: Deploy to Cloudflare Worker Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to Cloudflare Worker Pages
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.Cloudflare_ApiToken }}
          environment: 'production'
