name: Deploy to Cloudflare Worker Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Install dependencies
        uses: oven-sh/setup-bun@v1
        run: bun install

      - name: Build project
        uses: oven-sh/setup-bun@v1
        run: bun build

      - name: Deploy to Cloudflare Worker Pages
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: 'production'
